#pragma once

namespace KashipanEngine::KeyConfigDefineMaps {
#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>
#include <Xinput.h>
#include <string>
#include <unordered_map>

enum class MouseAnalogInputType {
    CursorX,
    CursorY,
    Wheel
};

enum class XInputAnalogInputType {
    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,
    LeftTrigger,
    RightTrigger,
    LeftThumbX = LeftStickX,
    LeftThumbY = LeftStickY,
    RightThumbX = RightStickX,
    RightThumbY = RightStickY
};

const std::unordered_map<std::string, int> kKeyboardKeyMap = {
    //--------- マクロ名でのマッピング ---------//
    {"DIK_ESCAPE", DIK_ESCAPE},
    {"DIK_1", DIK_1},
    {"DIK_2", DIK_2},
    {"DIK_3", DIK_3},
    {"DIK_4", DIK_4},
    {"DIK_5", DIK_5},
    {"DIK_6", DIK_6},
    {"DIK_7", DIK_7},
    {"DIK_8", DIK_8},
    {"DIK_9", DIK_9},
    {"DIK_0", DIK_0},
    {"DIK_MINUS", DIK_MINUS},
    {"DIK_EQUALS", DIK_EQUALS},
    {"DIK_BACK", DIK_BACK},
    {"DIK_TAB", DIK_TAB},
    {"DIK_Q", DIK_Q},
    {"DIK_W", DIK_W},
    {"DIK_E", DIK_E},
    {"DIK_R", DIK_R},
    {"DIK_T", DIK_T},
    {"DIK_Y", DIK_Y},
    {"DIK_U", DIK_U},
    {"DIK_I", DIK_I},
    {"DIK_O", DIK_O},
    {"DIK_P", DIK_P},
    {"DIK_LBRACKET", DIK_LBRACKET},
    {"DIK_RBRACKET", DIK_RBRACKET},
    {"DIK_RETURN", DIK_RETURN},
    {"DIK_LCONTROL", DIK_LCONTROL},
    {"DIK_A", DIK_A},
    {"DIK_S", DIK_S},
    {"DIK_D", DIK_D},
    {"DIK_F", DIK_F},
    {"DIK_G", DIK_G},
    {"DIK_H", DIK_H},
    {"DIK_J", DIK_J},
    {"DIK_K", DIK_K},
    {"DIK_L", DIK_L},
    {"DIK_SEMICOLON", DIK_SEMICOLON},
    {"DIK_APOSTROPHE", DIK_APOSTROPHE},
    {"DIK_GRAVE", DIK_GRAVE},
    {"DIK_LSHIFT", DIK_LSHIFT},
    {"DIK_BACKSLASH", DIK_BACKSLASH},
    {"DIK_Z", DIK_Z},
    {"DIK_X", DIK_X},
    {"DIK_C", DIK_C},
    {"DIK_V", DIK_V},
    {"DIK_B", DIK_B},
    {"DIK_N", DIK_N},
    {"DIK_M", DIK_M},
    {"DIK_COMMA", DIK_COMMA},
    {"DIK_PERIOD", DIK_PERIOD},
    {"DIK_SLASH", DIK_SLASH},
    {"DIK_RSHIFT", DIK_RSHIFT},
    {"DIK_MULTIPLY", DIK_MULTIPLY},
    {"DIK_LMENU", DIK_LMENU},
    {"DIK_SPACE", DIK_SPACE},
    {"DIK_CAPITAL", DIK_CAPITAL},
    {"DIK_F1", DIK_F1},
    {"DIK_F2", DIK_F2},
    {"DIK_F3", DIK_F3},
    {"DIK_F4", DIK_F4},
    {"DIK_F5", DIK_F5},
    {"DIK_F6", DIK_F6},
    {"DIK_F7", DIK_F7},
    {"DIK_F8", DIK_F8},
    {"DIK_F9", DIK_F9},
    {"DIK_F10", DIK_F10},
    {"DIK_NUMLOCK", DIK_NUMLOCK},
    {"DIK_SCROLL", DIK_SCROLL},
    {"DIK_NUMPAD7", DIK_NUMPAD7},
    {"DIK_NUMPAD8", DIK_NUMPAD8},
    {"DIK_NUMPAD9", DIK_NUMPAD9},
    {"DIK_SUBTRACT", DIK_SUBTRACT},
    {"DIK_NUMPAD4", DIK_NUMPAD4},
    {"DIK_NUMPAD5", DIK_NUMPAD5},
    {"DIK_NUMPAD6", DIK_NUMPAD6},
    {"DIK_ADD", DIK_ADD},
    {"DIK_NUMPAD1", DIK_NUMPAD1},
    {"DIK_NUMPAD2", DIK_NUMPAD2},
    {"DIK_NUMPAD3", DIK_NUMPAD3},
    {"DIK_NUMPAD0", DIK_NUMPAD0},
    {"DIK_DECIMAL", DIK_DECIMAL},
    {"DIK_OEM_102", DIK_OEM_102},
    {"DIK_F11", DIK_F11},
    {"DIK_F12", DIK_F12},
    {"DIK_F13", DIK_F13},
    {"DIK_F14", DIK_F14},
    {"DIK_F15", DIK_F15},
    {"DIK_KANA", DIK_KANA},
    {"DIK_ABNT_C1", DIK_ABNT_C1},
    {"DIK_CONVERT", DIK_CONVERT},
    {"DIK_NOCONVERT", DIK_NOCONVERT},
    {"DIK_YEN", DIK_YEN},
    {"DIK_ABNT_C2", DIK_ABNT_C2},
    {"DIK_NUMPADEQUALS", DIK_NUMPADEQUALS},
    {"DIK_PREVTRACK", DIK_PREVTRACK},
    {"DIK_AT", DIK_AT},
    {"DIK_COLON", DIK_COLON},
    {"DIK_UNDERLINE", DIK_UNDERLINE},
    {"DIK_KANJI", DIK_KANJI},
    {"DIK_STOP", DIK_STOP},
    {"DIK_AX", DIK_AX},
    {"DIK_UNLABELED", DIK_UNLABELED},
    {"DIK_NEXTTRACK", DIK_NEXTTRACK},
    {"DIK_NUMPADENTER", DIK_NUMPADENTER},
    {"DIK_RCONTROL", DIK_RCONTROL},
    {"DIK_MUTE", DIK_MUTE},
    {"DIK_CALCULATOR", DIK_CALCULATOR},
    {"DIK_PLAYPAUSE", DIK_PLAYPAUSE},
    {"DIK_MEDIASTOP", DIK_MEDIASTOP},
    {"DIK_VOLUMEDOWN", DIK_VOLUMEDOWN},
    {"DIK_VOLUMEUP", DIK_VOLUMEUP},
    {"DIK_WEBHOME", DIK_WEBHOME},
    {"DIK_NUMPADCOMMA", DIK_NUMPADCOMMA},
    {"DIK_DIVIDE", DIK_DIVIDE},
    {"DIK_SYSRQ", DIK_SYSRQ},
    {"DIK_RMENU", DIK_RMENU},
    {"DIK_PAUSE", DIK_PAUSE},
    {"DIK_HOME", DIK_HOME},
    {"DIK_UP", DIK_UP},
    {"DIK_PRIOR", DIK_PRIOR},
    {"DIK_LEFT", DIK_LEFT},
    {"DIK_RIGHT", DIK_RIGHT},
    {"DIK_END", DIK_END},
    {"DIK_DOWN", DIK_DOWN},
    {"DIK_NEXT", DIK_NEXT},
    {"DIK_INSERT", DIK_INSERT},
    {"DIK_DELETE", DIK_DELETE},
    {"DIK_LWIN", DIK_LWIN},
    {"DIK_RWIN", DIK_RWIN},
    {"DIK_APPS", DIK_APPS},
    {"DIK_POWER", DIK_POWER},
    {"DIK_SLEEP", DIK_SLEEP},
    {"DIK_WAKE", DIK_WAKE},
    {"DIK_WEBSEARCH", DIK_WEBSEARCH},
    {"DIK_WEBFAVORITES", DIK_WEBFAVORITES},
    {"DIK_WEBREFRESH", DIK_WEBREFRESH},
    {"DIK_WEBSTOP", DIK_WEBSTOP},
    {"DIK_WEBFORWARD", DIK_WEBFORWARD},
    {"DIK_WEBBACK", DIK_WEBBACK},
    {"DIK_MYCOMPUTER", DIK_MYCOMPUTER},
    {"DIK_MAIL", DIK_MAIL},
    {"DIK_MEDIASELECT", DIK_MEDIASELECT},
    {"DIK_BACKSPACE", DIK_BACKSPACE},
    {"DIK_NUMPADSTAR", DIK_NUMPADSTAR},
    {"DIK_LALT", DIK_LALT},
    {"DIK_CAPSLOCK", DIK_CAPSLOCK},
    {"DIK_NUMPADMINUS", DIK_NUMPADMINUS},
    {"DIK_NUMPADPLUS", DIK_NUMPADPLUS},
    {"DIK_NUMPADPERIOD", DIK_NUMPADPERIOD},
    {"DIK_NUMPADSLASH", DIK_NUMPADSLASH},
    {"DIK_RALT", DIK_RALT},
    {"DIK_UPARROW", DIK_UPARROW},
    {"DIK_PGUP", DIK_PGUP},
    {"DIK_LEFTARROW", DIK_LEFTARROW},
    {"DIK_RIGHTARROW", DIK_RIGHTARROW},
    {"DIK_DOWNARROW", DIK_DOWNARROW},
    {"DIK_PGDN", DIK_PGDN},
    {"DIK_CIRCUMFLEX", DIK_CIRCUMFLEX},

    //--------- キー名でのマッピング ---------//
    { "Escape", DIK_ESCAPE },
    { "Esc", DIK_ESCAPE },
    { "1", DIK_1 },
    { "2", DIK_2 },
    { "3", DIK_3 },
    { "4", DIK_4 },
    { "5", DIK_5 },
    { "6", DIK_6 },
    { "7", DIK_7 },
    { "8", DIK_8 },
    { "9", DIK_9 },
    { "0", DIK_0 },
    { "Minus", DIK_MINUS },
    { "-", DIK_MINUS },
    { "Equals", DIK_EQUALS },
    { "=", DIK_EQUALS },
    { "Back", DIK_BACK },
    { "Tab", DIK_TAB },
    { "Q", DIK_Q },
    { "W", DIK_W },
    { "E", DIK_E },
    { "R", DIK_R },
    { "T", DIK_T },
    { "Y", DIK_Y },
    { "U", DIK_U },
    { "I", DIK_I },
    { "O", DIK_O },
    { "P", DIK_P },
    { "LBracket", DIK_LBRACKET },
    { "[", DIK_LBRACKET },
    { "RBracket", DIK_RBRACKET },
    { "]", DIK_RBRACKET },
    { "Return", DIK_RETURN },
    { "Enter", DIK_RETURN },
    { "LControl", DIK_LCONTROL },
    { "A", DIK_A },
    { "S", DIK_S },
    { "D", DIK_D },
    { "F", DIK_F },
    { "G", DIK_G },
    { "H", DIK_H },
    { "J", DIK_J },
    { "K", DIK_K },
    { "L", DIK_L },
    { "Semicolon", DIK_SEMICOLON },
    { ";", DIK_SEMICOLON },
    { "Apostrophe", DIK_APOSTROPHE },
    { "'", DIK_APOSTROPHE },
    { "Grave", DIK_GRAVE },
    { "`", DIK_GRAVE },
    { "LShift", DIK_LSHIFT },
    { "Backslash", DIK_BACKSLASH },
    { "\\", DIK_BACKSLASH },
    { "Z", DIK_Z },
    { "X", DIK_X },
    { "C", DIK_C },
    { "V", DIK_V },
    { "B", DIK_B },
    { "N", DIK_N },
    { "M", DIK_M },
    { "Comma", DIK_COMMA },
    { ",", DIK_COMMA },
    { "Period", DIK_PERIOD },
    { ".", DIK_PERIOD },
    { "Slash", DIK_SLASH },
    { "/", DIK_SLASH },
    { "RShift", DIK_RSHIFT },
    { "Multiply", DIK_MULTIPLY },
    { "*", DIK_MULTIPLY },
    { "LMenu", DIK_LMENU },
    { "LAlt", DIK_LMENU },
    { "Space", DIK_SPACE },
    { "Capital", DIK_CAPITAL },
    { "F1", DIK_F1 },
    { "F2", DIK_F2 },
    { "F3", DIK_F3 },
    { "F4", DIK_F4 },
    { "F5", DIK_F5 },
    { "F6", DIK_F6 },
    { "F7", DIK_F7 },
    { "F8", DIK_F8 },
    { "F9", DIK_F9 },
    { "F10", DIK_F10 },
    { "NumLock", DIK_NUMLOCK },
    { "Num", DIK_NUMLOCK },
    { "Scroll", DIK_SCROLL },
    { "Numpad7", DIK_NUMPAD7 },
    { "Numpad8", DIK_NUMPAD8 },
    { "Numpad9", DIK_NUMPAD9 },
    { "Subtract", DIK_SUBTRACT },
    { "Numpad4", DIK_NUMPAD4 },
    { "Numpad5", DIK_NUMPAD5 },
    { "Numpad6", DIK_NUMPAD6 },
    { "Add", DIK_ADD },
    { "+", DIK_ADD },
    { "Numpad1", DIK_NUMPAD1 },
    { "Numpad2", DIK_NUMPAD2 },
    { "Numpad3", DIK_NUMPAD3 },
    { "Numpad0", DIK_NUMPAD0 },
    { "Decimal", DIK_DECIMAL },
    { "Oem102", DIK_OEM_102 },
    { "F11", DIK_F11 },
    { "F12", DIK_F12 },
    { "F13", DIK_F13 },
    { "F14", DIK_F14 },
    { "F15", DIK_F15 },
    { "Kana", DIK_KANA },
    { "AbntC1", DIK_ABNT_C1 },
    { "Convert", DIK_CONVERT },
    { "Noconvert", DIK_NOCONVERT },
    { "Yen", DIK_YEN },
    { "AbntC2", DIK_ABNT_C2 },
    { "Numpadequals", DIK_NUMPADEQUALS },
    { "Prevtrack", DIK_PREVTRACK },
    { "At", DIK_AT },
    { "@", DIK_AT },
    { "Colon", DIK_COLON },
    { ":", DIK_COLON },
    { "Underline", DIK_UNDERLINE },
    { "_", DIK_UNDERLINE },
    { "Kanji", DIK_KANJI },
    { "Stop", DIK_STOP },
    { "Ax", DIK_AX },
    { "Unlabeled", DIK_UNLABELED },
    { "Nexttrack", DIK_NEXTTRACK },
    { "NumpadEnter", DIK_NUMPADENTER },
    { "RControl", DIK_RCONTROL },
    { "Mute", DIK_MUTE },
    { "Calculator", DIK_CALCULATOR },
    { "PlayPause", DIK_PLAYPAUSE },
    { "MediaStop", DIK_MEDIASTOP },
    { "VolumeDown", DIK_VOLUMEDOWN },
    { "VolumeUp", DIK_VOLUMEUP },
    { "WebHome", DIK_WEBHOME },
    { "NumpadComma", DIK_NUMPADCOMMA },
    { "Divide", DIK_DIVIDE },
    { "Sysrq", DIK_SYSRQ },
    { "RMenu", DIK_RMENU },
    { "RAlt", DIK_RMENU },
    { "Pause", DIK_PAUSE },
    { "Home", DIK_HOME },
    { "Up", DIK_UP },
    { "Prior", DIK_PRIOR },
    { "Left", DIK_LEFT },
    { "Right", DIK_RIGHT },
    { "End", DIK_END },
    { "Down", DIK_DOWN },
    { "Next", DIK_NEXT },
    { "Insert", DIK_INSERT },
    { "Delete", DIK_DELETE },
    { "LWin", DIK_LWIN },
    { "RWin", DIK_RWIN },
    { "Apps", DIK_APPS },
    { "Power", DIK_POWER },
    { "Sleep", DIK_SLEEP },
    { "Wake", DIK_WAKE },
    { "WebSearch", DIK_WEBSEARCH },
    { "WebFavorites", DIK_WEBFAVORITES },
    { "WebRefresh", DIK_WEBREFRESH },
    { "WebStop", DIK_WEBSTOP },
    { "WebForward", DIK_WEBFORWARD },
    { "WebBack", DIK_WEBBACK },
    { "MyComputer", DIK_MYCOMPUTER },
    { "Mail", DIK_MAIL },
    { "MediaSelect", DIK_MEDIASELECT },
    { "BackSpace", DIK_BACKSPACE },
    { "NumpadStar", DIK_NUMPADSTAR },
    { "Lalt", DIK_LALT },
    { "Capslock", DIK_CAPSLOCK },
    { "Caps", DIK_CAPSLOCK },
    { "NumpadMinus", DIK_NUMPADMINUS },
    { "NumpadPlus", DIK_NUMPADPLUS },
    { "NumpadPeriod", DIK_NUMPADPERIOD },
    { "NumpadSlash", DIK_NUMPADSLASH },
    { "Ralt", DIK_RALT },
    { "UpArrow", DIK_UPARROW },
    { "Pgup", DIK_PGUP },
    { "LeftArrow", DIK_LEFTARROW },
    { "RightArrow", DIK_RIGHTARROW },
    { "DownArrow", DIK_DOWNARROW },
    { "Pgdn", DIK_PGDN },
    { "Circumflex", DIK_CIRCUMFLEX },
    { "^", DIK_CIRCUMFLEX },
};

const std::unordered_map<std::string, int> kMouseButtonIndexMap = {
    { "Left", 0 },
    { "LeftClick", 0 },
    { "LeftButton", 0 },
    { "Right", 1 },
    { "RightClick", 1 },
    { "RightButton", 1 },
    { "Middle", 2 },
    { "MiddleClick", 2 },
    { "MiddleButton", 2 },
    { "XButton1", 3 },
    { "XButton1Click", 3 },
    { "XButton2", 4 },
    { "XButton2Click", 4 },
    { "XButton3", 5 },
    { "XButton3Click", 5 },
    { "XButton4", 6 },
    { "XButton4Click", 6 }
};

const std::unordered_map<std::string, int> kMouseAnalogInputMap = {
    { "CursorX", 0 },
    { "CursorY", 1 },
    { "Wheel", 2 }
};

const std::unordered_map<std::string, int> kXInputButtonMap = {
    { "A", XINPUT_GAMEPAD_A },
    { "ButtonA", XINPUT_GAMEPAD_A },
    { "B", XINPUT_GAMEPAD_B },
    { "ButtonB", XINPUT_GAMEPAD_B },
    { "X", XINPUT_GAMEPAD_X },
    { "ButtonX", XINPUT_GAMEPAD_X },
    { "Y", XINPUT_GAMEPAD_Y },
    { "ButtonY", XINPUT_GAMEPAD_Y },
    { "Up", XINPUT_GAMEPAD_DPAD_UP },
    { "DPadUp", XINPUT_GAMEPAD_DPAD_UP },
    { "Down", XINPUT_GAMEPAD_DPAD_DOWN },
    { "DPadDown", XINPUT_GAMEPAD_DPAD_DOWN },
    { "Left", XINPUT_GAMEPAD_DPAD_LEFT },
    { "DPadLeft", XINPUT_GAMEPAD_DPAD_LEFT },
    { "Right", XINPUT_GAMEPAD_DPAD_RIGHT },
    { "DPadRight", XINPUT_GAMEPAD_DPAD_RIGHT },
    { "Start", XINPUT_GAMEPAD_START },
    { "Back", XINPUT_GAMEPAD_BACK },
    { "LeftThumb", XINPUT_GAMEPAD_LEFT_THUMB },
    { "RightThumb", XINPUT_GAMEPAD_RIGHT_THUMB },
    { "LeftShoulder", XINPUT_GAMEPAD_LEFT_SHOULDER },
    { "RightShoulder", XINPUT_GAMEPAD_RIGHT_SHOULDER }
};

const std::unordered_map<std::string, XInputAnalogInputType> kXInputAnalogInputMap = {
    { "LeftStickX", XInputAnalogInputType::LeftStickX },
    { "LeftStickY", XInputAnalogInputType::LeftStickY },
    { "RightStickX", XInputAnalogInputType::RightStickX },
    { "RightStickY", XInputAnalogInputType::RightStickY },
    { "LeftTrigger", XInputAnalogInputType::LeftTrigger },
    { "RightTrigger", XInputAnalogInputType::RightTrigger },
    { "LeftThumbX", XInputAnalogInputType::LeftThumbX },
    { "LeftThumbY", XInputAnalogInputType::LeftThumbY },
    { "RightThumbX", XInputAnalogInputType::RightThumbX },
    { "RightThumbY", XInputAnalogInputType::RightThumbY }
};

} // namespace KashipanEngine::KeyConfig